version: "3"

services:
    php:
        build:
            context: docker
            dockerfile: php.dockerfile
        restart: unless-stopped
        user: 1000:1000
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - backend

    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - backend

    postgres:
        image: postgres:15.2-alpine
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB_DATABASE}"
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    database:
        driver: local
